// Generated by CoffeeScript 2.6.1
var Simsimi, fetch;

fetch = require("node-fetch");

Simsimi = class Simsimi {
  constructor(token1) {
    this.token = token1;
  }

  request(content, language, token) {
    var tokenToUse;
    tokenToUse = token ? token : this.token;
    return new Promise(function(resolve, reject) {
      return fetch("https://api-sv2.simsimi.net/v2/", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": tokenToUse
        },
        body: JSON.stringify({
          text: content,
          lc: language ? language : "vn",
          cf:false
        })
      }).then(async function(res) {
        var data;
        data = (await res.json().catch(function() {
          return {};
        }));
        if (!data) {
          console.log((await res.text()));
        }
        return resolve(data);
      });
    });
  }

};

module.exports = Simsimi;
